### ISSUE TITLE
Will not install on Raspberry Pi running Python3.5

### ISSUE THREAD

**Issue by CrabbyPete** [adafruit/Adafruit_CircuitPython_RockBlock#20]
Collecting sysv-ipc (from Adafruit-Blinka->adafruit-circuitpython-rockblock)
  Using cached https://files.pythonhosted.org/packages/0c/d7/5d2f861155e9749f981e6c58f2a482d3ab458bf8c35ae24d4b4d5899ebf9/sysv_ipc-1.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-0bsmrbqa/sysv-ipc/setup.py", line 11, in <module>
        import prober
      File "/tmp/pip-build-0bsmrbqa/sysv-ipc/prober.py", line 137
        d["SYSV_IPC_VERSION"] = f'"{version}"'
                                             ^
    SyntaxError: invalid syntax

**Comment by CesMak** [comment]
Hm I have python 3.8.3 version and still get this error:

`
pi@pitwo:/usr/lib/python3/dist-packages $ pip3 install adafruit-circuitpython-dht
Collecting adafruit-circuitpython-dht


  Using cached https://www.piwheels.org/simple/adafruit-circuitpython-dht/adafruit_circuitpython_dht-3.7.1-py3-none-any.whl
Collecting Adafruit-Blinka (from adafruit-circuitpython-dht)
  Using cached https://www.piwheels.org/simple/adafruit-blinka/Adafruit_Blinka-5.13.1-py3-none-any.whl
Collecting RPi.GPIO (from Adafruit-Blinka->adafruit-circuitpython-dht)
  Downloading https://www.piwheels.org/simple/rpi-gpio/RPi.GPIO-0.7.1-cp35-cp35m-linux_armv6l.whl (68kB)
    100% |████████████████████████████████| 71kB 350kB/s 
Collecting rpi-ws281x>=4.0.0 (from Adafruit-Blinka->adafruit-circuitpython-dht)
  Using cached https://www.piwheels.org/simple/rpi-ws281x/rpi_ws281x-4.3.3-cp35-cp35m-linux_armv6l.whl
Collecting sysv-ipc (from Adafruit-Blinka->adafruit-circuitpython-dht)
  Using cached https://files.pythonhosted.org/packages/0c/d7/5d2f861155e9749f981e6c58f2a482d3ab458bf8c35ae24d4b4d5899ebf9/sysv_ipc-1.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-pzlnz5fh/sysv-ipc/setup.py", line 11, in <module>
        import prober
      File "/tmp/pip-build-pzlnz5fh/sysv-ipc/prober.py", line 137
        d["SYSV_IPC_VERSION"] = f'"{version}"'
                                             ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-pzlnz5fh/sysv-ipc/
pi@pitwo:/usr/lib/python3/dist-packages $ 
pi@pitwo:/usr/lib/python3/dist-packages $ 
pi@pitwo:/usr/lib/python3/dist-packages $ python3

`

**Comment by caternuson** [comment]
```
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-pzlnz5fh/sysv-ipc/
```
The install step is using `python` not `python3`. So determine what `python` is mapping to on your setup.

**Comment by InnerKing** [comment]
what do you mean

**Comment by caternuson** [comment]
The command `python` may invoke either Python2 or Python3 depending on system setup. A simple way to check is to run:
```
python --version
```
and see what version is shown. Python2 will have a 2.x.x release number. Python3 will have 3.x.x release number.

Python2 is not supported.
